//! Interop test: confirms the Rust license verifier accepts licenses
//! signed by the Node/TypeScript billing service.
//!
//! Fixtures are generated by `billing/src/interop_test.ts`. If the
//! payload format or signature scheme drifts between the two sides,
//! this test fails immediately.
//!
//! Because the embedded Rust pubkey is a compile-time constant (not
//! known until deploy), this test reconstructs verification using the
//! fixture's own public key rather than calling `license::verify`
//! directly.

use base64::Engine;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde_json::Value;
use std::fs;

const FIXTURE_PATH: &str = "tests/fixtures/license_fixture.json";
const FORGED_FIXTURE_PATH: &str = "tests/fixtures/license_forged_fixture.json";
const LICENSE_PREFIX: &str = "VOXLEN-";

fn load_fixture(path: &str) -> Value {
    let bytes = fs::read(path)
        .unwrap_or_else(|_| panic!("missing fixture {path}: run `npm run interop` in billing/"));
    serde_json::from_slice(&bytes).expect("fixture is not valid JSON")
}

fn split_license(license: &str) -> (Vec<u8>, Vec<u8>) {
    let body = license
        .strip_prefix(LICENSE_PREFIX)
        .expect("license must have VOXLEN- prefix");
    let (payload_b64, sig_b64) = body.split_once('.').expect("license missing signature");
    let engine = base64::engine::general_purpose::URL_SAFE_NO_PAD;
    let payload = engine.decode(payload_b64).expect("payload not base64url");
    let signature = engine.decode(sig_b64).expect("signature not base64url");
    (payload, signature)
}

fn pubkey_from_hex(hex: &str) -> VerifyingKey {
    let bytes = hex::decode(hex).expect("pubkey not hex");
    let arr: [u8; 32] = bytes.try_into().expect("pubkey not 32 bytes");
    VerifyingKey::from_bytes(&arr).expect("invalid Ed25519 public key")
}

#[test]
fn node_signed_license_verifies_in_rust() {
    let fixture = load_fixture(FIXTURE_PATH);
    let pubkey_hex = fixture["publicKeyHex"].as_str().unwrap();
    let license = fixture["license"].as_str().unwrap();

    let (payload, signature) = split_license(license);
    let key = pubkey_from_hex(pubkey_hex);
    let sig_arr: [u8; 64] = signature.as_slice().try_into().expect("signature not 64 bytes");
    let sig = Signature::from_bytes(&sig_arr);

    key.verify(&payload, &sig)
        .expect("Node-signed license must verify against its public key");

    // And the payload round-trips the same shape.
    let parsed: Value = serde_json::from_slice(&payload).expect("payload is JSON");
    assert_eq!(parsed["tier"].as_str(), fixture["payload"]["tier"].as_str());
    assert_eq!(parsed["email"].as_str(), fixture["payload"]["email"].as_str());
    assert_eq!(parsed["id"].as_str(), fixture["payload"]["id"].as_str());
}

#[test]
fn forged_license_is_rejected() {
    let fixture = load_fixture(FORGED_FIXTURE_PATH);
    let pubkey_hex = fixture["publicKeyHex"].as_str().unwrap();
    let license = fixture["license"].as_str().unwrap();

    let (payload, signature) = split_license(license);
    let key = pubkey_from_hex(pubkey_hex);
    let sig_arr: [u8; 64] = signature.as_slice().try_into().expect("signature not 64 bytes");
    let sig = Signature::from_bytes(&sig_arr);

    assert!(
        key.verify(&payload, &sig).is_err(),
        "license signed by a different keypair must NOT verify"
    );
}
